MagicStack/asyncpg

- asyncpg/connection.py
> Add Amazon Redshift detection.

- asyncpg/pool.py
- tests/test_pool.py
Specifically Pool now implements the following methods:
* Pool.execute()
* Pool.executemany()
* Pool.fetch()
* Pool.fetchrow()
* Pool.fetchval()
> Expose some of Connection methods directly on the Pool object.

- asyncpg/connection.py
> Make timeout in connect() consistent.

- asyncpg/protocol/codecs/base.pyx
- tests/test_codecs.py
set_builtin_type_codec() flushes the codec cache, so internal codec
aliasing (for enums and fallback) must use a version that doesn't
kill the cache.
Fixes: #133.
> Fix erroneous codec cache invalidation on internal codec aliasing.

- asyncpg/pool.py
- tests/test_pool.py
Specifically, allow proxied Connection objects to use overridden
public methods.
> Make PoolConnectionProxy more dynamic. Fixes #155.

- tests/test_pool.py
This is to see if #202 reproduces in CI.
> Add a test for run_until_complete(asyncpg.create_pool())

- docs/usage.rst
Thanks to Adam Rothman (@adamrothman) for providing this.
Closes: #245
> Add an example of setting a codec for PostGIS types.

- .ci/travis-build-docs.sh
- asyncpg/connection.py
Fix a few broken external links while at it.
Closes: #265
> Add a link to Postgres docs for server_settings connect argument

- asyncpg/protocol/codecs/datetime.pyx
- tests/test_codecs.py
- tests/test_connect.py
> Allow passing datetime.date instances as timestamp input

- asyncpg/pool.py
- tests/test_pool.py
Raise an InterfaceError if:
* Two or more tasks try to initialize the same Pool object concurrently;
* A pool method, such as fetchval(), is called while the Pool is being
initialized.
See also issue #320.
> Raise a clear error if there's a race in pool intialization.

- asyncpg/connect_utils.py
- tests/test_connect.py
> Handle and ignore permission errors when attempting to read .pgpass

- asyncpg/protocol/codecs/datetime.pyx
- tests/test_codecs.py
The datetime decoder currently incorrectly uses an unsigned integer type
for microseconds, which leads to incorrect decoding of timestamps with
fractional seconds which represent dates before Jan 1 2000.  Same issue
affects negative intervals with fractional seconds.
Fixes: #363
> Fix decoding of fractional timestamps before Postgres epoch

- asyncpg/connect_utils.py
- tests/test_connect.py
Basic support for libpq-like handling of 'sslmode' parameter.
It uses default ssl contexts, rather than reading ~/.postgres files
or other 'ssl*' parameters like libpq would.
> Allow 'sslmode' in DSNs

- asyncpg/protocol/codecs/array.pyx
- asyncpg/protocol/codecs/base.pxd
- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/codecs/range.pyx
- asyncpg/protocol/codecs/record.pyx
- asyncpg/protocol/coreproto.pyx
- asyncpg/protocol/prepared_stmt.pxd
- asyncpg/protocol/prepared_stmt.pyx
- asyncpg/protocol/protocol.pxd
- asyncpg/protocol/protocol.pyx
* Switch to a new FBBuffer abstraction
* Drop Memory object
* Start using new ReadBuffer.discard_message()
> Bump pgproto version 

- asyncpg/pool.py
> fix for warning_callback not yet defined

- .travis.yml
- README.rst
- asyncpg/_testbase/__init__.py
- asyncpg/cluster.py
- asyncpg/exceptions/__init__.py
- docs/index.rst
PostgreSQL has a couple of incompatible configuration changes so adjust
to that.  Also, the new JIT is messing up with test timings, so disable
it explicitly for the testsuite on 11+.
> Add PostgreSQL 12 support

- asyncpg/connect_utils.py
Add back one line from what seems to be a bad merge.
https://github.com/MagicStack/asyncpg/issues/509
> Add back ensure future for connector

- asyncpg/connection.py
> fix connection links

- setup.py
https://github.com/MagicStack/asyncpg/issues/649
> fix(pgproto): bump version to fix pyinstaller

- .github/workflows/release.yml
- asyncpg/_version.py
Changes
-------
* Add support to use awaitable object in password function.   (#889)
(by @kwarunek in fb3b6bf7 for #889)
* Support direct TLS connections (i.e. no STARTTLS) (#923)
(by @jackwotherspoon in f2a937d2 for #923)
Fixes
-----
* Fix invalid `pyproject.toml` (#900)
(by @Rongronggg9 in eddb649c for #900)
* Add `record_class` parameter Pool.fetch and Pool.fetchrow (#896)
(by @baltitenger in 2519cf38 for #896)
* Domain basetypes are introspected (#886) (#887)
(by @QuantumTM in cca4a2d3 for #886)
* Properly handle exceptions raised while handling server auth messages (#862)
(by @elprans in bd192623 for #862)
> asyncpg v0.26.0

- tests/test_connect.py
Context: https://github.com/python/cpython/issues/78182
> Fix test_tls_version for LibreSSL

- .github/workflows/release.yml
- asyncpg/_version.py
Minor fixes and improvements.
Changes
=======
* Do not try to cleanup statements (#981)
(by @fvannee in d2e710fe for #981)
* Add Pool.is_closing() method (#973)
(by @singingwolfboy in 9cb2c1ce for #973)
* Fix test_tls_version for LibreSSL (#974)
(by @CyberTailor in 7df9812a for #974)
* Handle environments without home dir (#1011)
(by @LeonardBesson in 172b8f69 for #1011)
* fix: salt and iterations parsing for scram (#1026)
(by @trigonometr in 7443a9e7 for #1026)
* Add support for target_session_attrs (#987)
(by @JesseDeLoore in bf74e88b for #987)
* Add support for READ UNCOMMITTED (#1039)
(by @benwah in 2f20bae7 for #1039)
* Update benchmarks, add psycopg3 (#1042)
(by @elprans in 7d4fcf04 for #1042)
> asyncpg v0.28.0

- pyproject.toml
> Remove empty line
