MagicStack/asyncpg

- asyncpg/types.py
I was reading the code and I'm pretty sure this is an error.
However, be warned: this change has not been tested.
> Fixed copy-and-paste error in Line type

- asyncpg/cluster.py
as reported in https://bugs.debian.org/843967 this pull request will fix parsing cluster's PID in some locales
> Fix parsing pg_ctl output in some locales

- asyncpg/connection.py
- asyncpg/protocol/coreproto.pxd
- asyncpg/protocol/coreproto.pyx
- asyncpg/protocol/protocol.pyx
- tests/test_execute.py
The executemany() method runs an SQL command for each sequence
of arguments in the given iterable.
Closes: #36
> Implement the Connection.executemany() method

- asyncpg/_testbase.py
- asyncpg/cluster.py
- asyncpg/connection.py
- tests/test_pool.py
> Fix Connection.reset() on read-only connections

- asyncpg/serverversion.py
- tests/test_connect.py
It seems broken from the beginning:
d4a66cbd948c45d8ff43f5a383a7ce9b189f08b8
Detect numbers by both sides of a string in the last part
(they are not split[1] by '.').
Also update parsing version string for Postgres ver>=10 (no minor part[2][3]).
[1] 9.4beta2
https://git.postgresql.org/pg/commitdiff/c85374626f680902c207285b986ac38a134535eb
[2] 10devel
https://git.postgresql.org/pg/commitdiff/ca9112a424ff68ec4f2ef67b47122f7d61412964
[3] new numbering scheme:
discussion:
https://www.postgresql.org/message-id/flat/7684.1470066581%40sss.pgh.pa.us
example:
https://git.postgresql.org/pg/commitdiff/69dc5ae408f68c302029a6b43912a2cc16b1256c
> Fix parsing server version string for non-final releases (devel, beta etc.)

- asyncpg/protocol/buffer.pxd
- asyncpg/protocol/buffer.pyx
- asyncpg/protocol/codecs/array.pyx
- asyncpg/protocol/codecs/base.pxd
- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/codecs/text.pyx
- asyncpg/protocol/codecs/textutils.pyx
- tests/test_codecs.py
Currently, asyncpg supports falling back to text I/O for types that do not have a registered codec.  This commit extends this behaviour to arrays of such types.
Additionally, add an explicit error for when the text I/O is attempted for a range or a composite type, as these are not supported yet.
> Add support for the text I/O fallback for arrays of unknown types.

- asyncpg/protocol/coreproto.pyx
- tests/test_execute.py
> Handle exceptions in generators passed to Connection.executemany()

- asyncpg/connection.py
- asyncpg/protocol/settings.pyx
- asyncpg/types.py
Add basic server capability detection mechanism based on server version
and parameters reported by the server through ParameterStatus messages.
This allows altering certain asyncpg behaviour based on the connected
server.
Specifically, this allows asyncpg to connect to CockroachDB servers.
Fixes #87.
> Add rudimentary server capability detection.

- asyncpg/__init__.py
- asyncpg/protocol/__init__.py
- asyncpg/protocol/protocol.pyx
- asyncpg/protocol/record/__init__.pxd
- asyncpg/protocol/record/recordobj.c
- asyncpg/protocol/record/recordobj.h
- docs/api/index.rst
- tests/test_record.py
> Make the Record type available as asyncpg.Record.

- asyncpg/_testbase.py
- asyncpg/connection.py
- asyncpg/pool.py
- tests/test_pool.py
Use asyncio.shield() to guarantee that task cancellation
does not prevent the connection from being returned to the
pool properly.
Fixes: #97.
> Shield Pool.release() from task cancellation.

- asyncpg/connection.py
- asyncpg/pool.py
- tests/test_connect.py
- tests/test_pool.py
Connection pool now wraps all connections in `PooledConnectionProxy` objects to raise `InterfaceError` if they are used after being released back to the pool.  We also check if connection passed to `pool.release` actually belong to the pool and correctly handle multiple calls to `pool.release` with the same connection object.
`PooledConnectionProxy` transparently wraps Connection instances, exposing all Connection public API.
`isinstance(asyncpg.connection.Connection)` is `True` for Instances of `PooledConnectionProxy` class.
> pool: Track connections and prohibit using them after release.

- asyncpg/pool.py
- tests/test_pool.py
Make internal connection pool queue reference a new intermediate
object -- PoolConnectionHolder -- instead of Connections directly.
PoolConnectionHolder fully encapsulates the management of one
connection:
* connection logic;
* handling closed connections;
* handling connections that exceeded max-queries quota; etc.
The new logic guarantees that old and new connections are always
added back to the pool (1), removes a deadlock in pool.acquire (2),
uses a LIFO queue to take advantage of "min_size" pool parameter.
> pool: Add another level of indirection to the pool internal logic

- asyncpg/connection.py
- asyncpg/exceptions/__init__.py
- asyncpg/exceptions/_base.py
- asyncpg/pool.py
- asyncpg/prepared_stmt.py
- asyncpg/protocol/protocol.pyx
- tests/test_cache_invalidation.py
- tests/test_prepare.py
- tools/generate_exceptions.py
PostgreSQL will raise an exception when it detects that the result type of the
query has changed from when the statement was prepared.  This may happen, for
example, after an ALTER TABLE or SET search_path.
When this happens, and there is no transaction running, we can simply
re-prepare the statement and try again.
If the transaction _is_ running, this error will put it into an error state,
and we have no choice but to raise an exception.  The original error is
somewhat cryptic, so we raise a custom InvalidCachedStatementError with the
original server exception as context.
In either case we clear the statement cache for this connection and all other
connections of the pool this connection belongs to (if any).
See #72 and #76 for discussion.
Fixes: #72.
> Invalidate statement cache on schema changes affecting statement result.

- asyncpg/connection.py
- asyncpg/protocol/__init__.py
- asyncpg/protocol/protocol.pxd
- asyncpg/protocol/protocol.pyx
- tests/test_timeout.py
The timeout logic is currently a bit of a mess.  This commit attempts to
tidy things up.
Most importantly, the timeout budget is now applied consistently to the
_entire_ call, whereas previously multiple consecutive operations used
the same timeout value, making it possible for the overall run time to
exceed the timeout.
Secondly, tighten the validation for timeouts: booleans are not
accepted, and neither any value that cannot be converted to float.
> Implement conistent handling of timeouts.

- asyncpg/connection.py
- tests/test_execute.py
Backwards compatibility will be preserved until 0.11.
> Make 'timeout' arg of Connection.executemany a keyword-only arg.

- asyncpg/_testbase.py
- asyncpg/connection.py
- tests/test_prepare.py
- tests/test_timeout.py
The parameter allows asyncpg to refresh cached prepared statements
periodically.
See also issue #76.
> Add new `max_cached_statement_use_count` parameter to Connection.

- asyncpg/connection.py
- tests/test_connect.py
- tests/test_prepare.py
> Add new Connection parameter: `max_cacheable_statement_size`.

- asyncpg/pool.py
- tests/test_connect.py
> Fix SSL support in connection pool.

- asyncpg/__init__.py
- asyncpg/_testbase.py
- asyncpg/connect_utils.py
- asyncpg/connection.py
- asyncpg/pool.py
- asyncpg/protocol/coreproto.pxd
- asyncpg/protocol/coreproto.pyx
- asyncpg/protocol/protocol.pyx
- tests/test_connect.py
- tests/test_pool.py
- tests/test_timeout.py
Added:
* `connection_class` parameter to connect() and create_pool() to
specify a custom Connection object.
* `server_settings` parameter to connect() and create_pool() to
set custom server connection settings.
Fixed:
* Connection pool to always create Connections with correct
configuration.  Before, the pool could lose parameters like
`statement_cache_size`.
Backwards Compatibility:
* connect() and create_pool() no longer accept arbitrary
keyword arguments for server settings. Use new `server_settings`
argument for that.
> Refactor args parsing and config management for connect and create_pool

- asyncpg/compat.py
- asyncpg/connection.py
- asyncpg/protocol/buffer.pxd
- asyncpg/protocol/buffer.pyx
- asyncpg/protocol/coreproto.pxd
- asyncpg/protocol/coreproto.pyx
- asyncpg/protocol/protocol.pxd
- asyncpg/protocol/protocol.pyx
- asyncpg/protocol/python.pxd
- asyncpg/utils.py
- docs/conf.py
- tests/test_copy.py
- tests/test_utils.py
This commit adds two new Connection methods: copy_from_table() and
copy_from_query() that allow copying the contents of a table or
the results of a query using PostgreSQL COPY protocol.
Issue #21.
> Add support for COPY OUT

- asyncpg/protocol/codecs/int.pyx
- tests/test_codecs.py
During development I got strange results when some integer values are passed as query parameters.
I expected `0xfffffffe` as `int4` should raise an exception, but it saved as "-2". Moreover, `0xffffffffe` (there is one "`f`" more) gave the same result.
It was understandable that it is a result of a wrong typecasting.
Debugging led to this PR. Almost all comments are in commit messages.
Firstly I tried to use `PyLong_AsLongAndOverflow` and `PyLong_AsLongLongAndOverflow` but could not reraise exceptions if they are not connected with overflowing. That is why "`try..except`" is used here.
To make the code be compatible between systems I use `sizeof(val) > X` to make a compiler optimize the rest of a condition.
Also I think it is wise to have the same exception among all ranges (previously …
> Fix integer boundaries

- asyncpg/protocol/record/recordobj.c
- tests/test_record.py
> Fix Record.keys() and Record.items() to correctly handle duplicate field names.

- asyncpg/protocol/codecs/base.pxd
- asyncpg/protocol/codecs/base.pyx
- tests/test_codecs.py
When a custom codec is set for a type, it should be called regardless of
whether its format matches the preferred format requested by the
pipeline.
Fixes: #140
Fixes: #148
> Make sure set_type_codec() overrides core codec for all formats.

- asyncpg/connection.py
- asyncpg/exceptions/_base.py
- asyncpg/protocol/coreproto.pxd
- asyncpg/protocol/coreproto.pyx
- asyncpg/protocol/protocol.pyx
- tests/test_listeners.py
- tests/test_pool.py
Per request #144.
It seems I implemented it long time ago, but did not have enough time to finalize it as a PR.
I think a single callback per connection is enough, therefore API has just `set_notice_callback` instead of `add_notice_callback` and `remove_notice_callback`.
P.S.: Here is also two minor commits small enough to create separated PRs.
> Add API for receiving asynchronous notices

- asyncpg/protocol/codecs/datetime.pyx
- tests/test_codecs.py
asyncpg will now treat 12-month interval increments as 365-day spans,
instead of 12*30 day spans.  This matches psycopg2 interval decoding
logic.
> Make interval decoding logic match that of psycopg2.

- asyncpg/connection.py
- asyncpg/protocol/codecs/base.pxd
- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/codecs/datetime.pyx
- asyncpg/protocol/settings.pxd
- asyncpg/protocol/settings.pyx
- docs/.gitignore
- docs/_static/theme_overrides.css
- docs/conf.py
- tests/test_codecs.py
Connection.set_type_codec() now accepts a new `format` keyword
argument.  When set to 'tuple', it declares that the custom codec
exchanges data with the driver in a type-specific tuple format.
This allows using custom codecs for types without the need to parse
the raw binary or text data format.
This commit adds tuple exchange support for all date-time types.
The `binary` keyword argument to set_type_codec() is now deprecated
in favor of `format='text'` and `format='binary'`.
> Add support for tuple exchange format for codec overrides

- asyncpg/connection.py
- asyncpg/exceptions/__init__.py
- asyncpg/exceptions/_base.py
- asyncpg/protocol/protocol.pyx
- tests/test_listeners.py
- tools/generate_exceptions.py
1. Rename to `Connection.add_log_listener()`
2. Fix `Connection.reset()` to reset log listeners
3. Add a new `PostgresLogMessage` class for log messages
4. Instances of `PostgresLogMessage` are immutable
5. Regenerate `exceptions/__init__`; `PostgresWarning` is now a subclass of `PostgresLogMessage`.
> Refactor Connection.add_notice_callback API.

- asyncpg/connection.py
- asyncpg/protocol/codecs/datetime.pyx
- tests/test_codecs.py
This makes interval consistent with other datetime types.
> Do not split out seconds when decoding interval in tuple mode.

- asyncpg/connect_utils.py
- tests/test_connect.py
When the host is not passed explicitly to `connect()`, asyncpg tries
to find a suitable socket in a few known directories.  On Windows, where
there are no file sockets, we should connect directly to 'localhost'
instead.
Fixes: #184.
> Do not attempt to connect to Unix sockets on Windows when host is not set

- LICENSE
Hopefully, this will fix Github's detection.  Sync the copyright line
with that of the license header.
[ci skip]
> Update LICENSE text to match the canonical Apache 2.0 blob

- asyncpg/protocol/prepared_stmt.pyx
- tests/test_prepare.py
> Clarify the argument/parameter count mismatch exception

- asyncpg/protocol/prepared_stmt.pyx
- tests/test_codecs.py
Or it will raise:
```
File "asyncpg/prepared_stmt.py", line 89, in get_attributes
return self._state._get_attributes()
File "asyncpg/protocol/prepared_stmt.pyx", line 41, in asyncpg.protocol.protocol.PreparedStatementState._get_attributes
TypeError: 'NoneType' object is not iterable
```
> Fix `TypeError` on `get_attributes` when result has no columns

- .ci/package-version.py
- asyncpg/__init__.py
- docs/conf.py
- setup.py
Yes, we could use `pkg_resources`, but that imposes a serious slowdown, see [this issue](https://github.com/pypa/setuptools/issues/510) for context.
> Allow grabbing the version information programmatically.

- asyncpg/connection.py
- tests/test_introspection.py
Type introspection queries now rely on the general statement cache
instead of ad-hoc prepared statements.
Fixes: #198.
> Use the general statement cache for type introspection

- asyncpg/protocol/codecs/network.pyx
- tests/test_codecs.py
The inet codec is confusing the network prefix length with the network
mask length, which causes incorrect wire encoding.  This was masked by a
symmetrical bug in the decoder.
Fixes #37.
> Fix issues with inet type I/O

- asyncpg/pool.py
- tests/test_pool.py
> Handle inactive connection closes while stored in the pool

- asyncpg/connection.py
- tests/test_codecs.py
set_type_codec(..., binary=True) was deprecated in 0.12.0.
> Remove the deprecated "binary" parameter from Connection.set_type_codec

- .github/ISSUE_TEMPLATE.md
- asyncpg/exceptions/_base.py
- asyncpg/transaction.py
- docs/api/index.rst
- docs/faq.rst
- docs/usage.rst
- tests/test_prepare.py
Related issues: #121 and #149.
> Document pgbouncer-related prepared statement breakage

- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/codecs/record.pyx
- asyncpg/protocol/hton.h
- asyncpg/protocol/hton.pxd
- setup.py
Per report in #216 and https://bugs.debian.org/872408, the current
implementation may raise SIGBUS on ARM platforms that do not support
unaligned memory access.
Fix this by using a stack variable and memcpy, which gives the compiler
more opportunity to generate correct code.  While at it, implement
hton* and ntoh* in terms of byteswap intrinsics with an open-coded
fallback.  This drops the dependency on the platform's implementation,
which might not necessarily be consistently fast.
Smoke-tested locally on cross-compiled armv5tel-softfloat-linux-gnueabi
and armv6j-hardfloat-linux-gnueabi with QEMU TCG.
Fixes: #216.
> Fix unaligned access issues in host-network byte I/O on ARM

- asyncpg/connection.py
To support connection pooling if used with
https://github.com/crate/crate
This depends on https://github.com/crate/crate/pull/6476
(So this will only work starting with CrateDB 2.3)
ParameterDescription support in CrateDB is also a bit limited - so certain queries might still not work.
> Add CrateDB detection

- asyncpg/serverversion.py
- tests/test_connect.py
Since PostgreSQL 10 the versioning scheme has changed, and 10.x really means 10.0.x.  While parsing 10.1 as `(10, 1)` may seem less confusing, in practice most version checks are written as `version[:2]`, and we want to keep that behaviour consistent, i.e. not fail a major version check due to a bugfix release.
> Parse server version x.y as x.0.y, when x is >= 10

- asyncpg/protocol/codecs/datetime.pyx
- asyncpg/serverversion.py
- tests/test_codecs.py
- tests/test_connect.py
For timetz an offset is applied to a time itself, it is not a time zone offset.
This was masked by a symmetrical bug in the encoder.
An offset value is still passed in a tuple (timetz_decode_tuple) as it was
received from Postgres.
> Fix issues with timetz type I/O

- .ci/appveyor.yml
- .ci/requirements-win.txt
- .ci/requirements.txt
- .ci/travis-install.sh
- .gitignore
- asyncpg/_testbase.py
- asyncpg/_testbase/__init__.py
- asyncpg/_testbase/fuzzer.py
- asyncpg/cluster.py
- asyncpg/connection.py
- asyncpg/pool.py
- asyncpg/protocol/protocol.pyx
- tests/test_adversity.py
- tests/test_codecs.py
- tests/test_connect.py
- tests/test_execute.py
- tests/test_introspection.py
- tests/test_pool.py
- tests/test_prepare.py
- tests/test_timeout.py
`Connection.close()` and `Pool.release()` each gained the new `timeout`
parameter.  The `pool.acquire()` context manager now applies the
passed timeout to `__aexit__()` as well.
`Connection.close()` is now actually graceful.  Instead of simply dropping
the connection, it attempts to cancel the running query (if any), asks
the server to terminate the connection and waits for the connection to
terminate.
To test all this properly, implement a TCP proxy, which emulates sudden
connectivity loss (i.e. packets not reaching the server).
Closes: #220
> Support timeouts in Connection.close() and Pool.release()

- asyncpg/types.py
- tests/test_codecs.py
fixes #230
remove `other` from parameter list of `__hash__`
> fix Range.__hash__

- asyncpg/connection.py
- asyncpg/connresource.py
- asyncpg/pool.py
- asyncpg/transaction.py
- tests/test_pool.py
Similarly to other connection-dependent objects, transaction methods
should not be called once the underlying connection has been released to
the pool.
Also, add a special handling for the case of asynchronous generator
finalization, in which case it's OK for `Transaction.__aexit__()` to be
called _after_ `Pool.release()`, since we cannot control when the
finalization task would execute.
Fixes: #232.
> Guard transaction methods against underlying connection release

- asyncpg/connection.py
- asyncpg/exceptions/_base.py
- asyncpg/prepared_stmt.py
- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/settings.pxd
- asyncpg/protocol/settings.pyx
- setup.py
- tests/test_cache_invalidation.py
Almost all explanation is written in the commit message.
The rest I want to mention is at least one feature is left untouched. It is the `BaseCursor` where the `bind_execute` and `bind` calls should be wrapped by the same way the `bind_execute` in the `PreparedStatement.__bind_execute` was, but I'd leave it for the other commit (may be by the other author).
> Invalidate type cache on schema changes affecting statement result.

- asyncpg/connection.py
- tests/test_cache_invalidation.py
- tests/test_prepare.py
This is to address: https://github.com/MagicStack/asyncpg/issues/243
I think is the most sane solution for people wanting to bypass the statement cache for individual queries.
> Connection.prepare should not use statement cache

- asyncpg/connection.py
- asyncpg/protocol/prepared_stmt.pxd
- asyncpg/protocol/prepared_stmt.pyx
- asyncpg/protocol/protocol.pyx
- tests/test_introspection.py
Currently the statement codecs are populated just before the first Bind
is issued.  This is problematic as in the time since Prepare, the codec
cache for derived types (arrays, composites etc.) may have been purged
by an installation of a custom codec, or general schema state
invalidation.
Fix this by populating the codecs immediately after the statement data
types have been resolved.
Fixes: #241.
> Initialize statement codecs immediately after Prepare

- asyncpg/serverversion.py
- tests/test_connect.py
Some distros (e.g Debian) like may inject their branding
into the numeric version string, so make sure to only look
at stuff before the first space.
Fixes: #250.
> Fix server version parsing when it contains trailing data

- asyncpg/__init__.py
- asyncpg/protocol/codecs/array.pyx
- tests/test_codecs.py
Make the array input type check for correct ABCs instead of producing a
cryptic error when a non-iterable container is passed.
> Prohibit non-iterable containers to be passed as array input

- asyncpg/__init__.py
- asyncpg/compat.py
- asyncpg/connect_utils.py
- asyncpg/connection.py
- tests/test_connect.py
This largely mirrors libpq's behaviour with respect to ~/.pgpass.
Fixes: #267.
> Add support for reading passwords from .pgpass

- asyncpg/protocol/codecs/tid.pyx
- tests/test_codecs.py
Refs #285, postgres is using unsigned ints for block and offset, so changing codec for `tid` to be consistent with postgres. Using [PyLong_AsUnsignedLong](https://docs.python.org/3/c-api/long.html#c.PyLong_AsUnsignedLong) instead, thus losing the support for `Decimal` which I think is not a problem.
References:
* https://github.com/postgres/postgres/blob/REL_10_STABLE/src/include/storage/block.h
* https://github.com/postgres/postgres/blob/REL_10_STABLE/src/include/storage/off.h
> Use unsigned int for tid

- .ci/requirements-win.txt
- .ci/requirements.txt
- asyncpg/protocol/protocol.pyx
- requirements-dev.txt
- setup.py
Start using the new @cython.iterable_coroutine decorator. This allows
us to stop patching the generated C code to get compatibility with
generator-based coroutines.
> Upgrade to Cython 0.28.2

- asyncpg/__init__.py
- asyncpg/connection.py
- tests/test_transaction.py
Added method checking the state of `_top_xact`.
I'm not familiar with the library's version number usage, so I just bumped the lowest element of the version number.  Correct me if this is wrong.
> expose method is_in_transaction

- asyncpg/_testbase/__init__.py
- asyncpg/cluster.py
- asyncpg/connection.py
- asyncpg/introspection.py
- asyncpg/protocol/buffer.pxd
- asyncpg/protocol/buffer.pyx
- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/codecs/int.pyx
- asyncpg/protocol/codecs/misc.pyx
- asyncpg/protocol/codecs/tid.pyx
- asyncpg/protocol/prepared_stmt.pyx
- asyncpg/protocol/protocol.pyx
- tests/test_codecs.py
- tests/test_connect.py
- tests/test_pool.py
Currently asyncpg (incorrectly) assumes OIDs to be signed 32-bit
integers, whereas in reality they are unsigned.  As a result, things
would crash once the OID sequence reaches 2**31.
Fix this by decoding OID values as unsigned longs.
Fixes: #279
> Fix handling of OIDs >= 2**31

- asyncpg/connection.py
- asyncpg/pool.py
- tests/test_adversity.py
- tests/test_cache_invalidation.py
- tests/test_pool.py
Currently, `pool.close()`, despite the "graceful" designation, closes
all connections immediately regardless of whether they are acquired.
With this change, pool will wait for connections to actually be released
before closing.
WARNING: This is a potentially incompatible behavior change, as sloppily
written code which does not release acquired connections will now cause
`pool.close()` to hang forever.
Also, when `conn.close()` or `conn.terminate()` are called directly
on an acquired connection, the associated pool item is released
immediately.
Closes: #290
> Make Pool.close() wait until all checked out connections are released

- asyncpg/connection.py
- asyncpg/pool.py
- asyncpg/protocol/codecs/base.pxd
- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/prepared_stmt.pyx
- asyncpg/protocol/settings.pxd
- tests/test_introspection.py
Current global type codec cache works poorly in a pooled environment.
The global nature of the cache makes introspection/cache bust race a
frequent occurrence.  Additionally, busting the codec cache in _all_
connections only because one of them had reconfigured a codec seems
wrong.
The fix is simple: every connection now has its own codec cache.  The
downside is that there will be more introspection queries on fresh
connections, but given that most connections in the field are pooled,
the robustness gains are more important.
Fixes: #278
> Fix type codec cache races

- asyncpg/exceptions/_base.py
- asyncpg/protocol/codecs/float.pyx
- asyncpg/protocol/codecs/int.pyx
- asyncpg/protocol/codecs/tid.pyx
- asyncpg/protocol/prepared_stmt.pyx
- tests/test_codecs.py
Currently, when invalid input is passed a query argument, asyncpg will
raise whatever exception was triggered by the codec function, which
can be `TypeError`, `ValueError`, `decimal.InvalidOperation` etc.
Additionally, these exceptions lack sufficient context as to which
argument actually triggered an error.
Fix this by consistently raising the new `asyncpg.DataError` exception,
which is a subclass of `asyncpg.InterfaceError` and `ValueError`, and
include the position of the offending argument as well as the passed
value, e.g:
asyncpg.exceptions.DataError: invalid input for query argument $1: 'aaa'
(a bytes-like object is required, not 'str')
Fixes: #260
> Raise a consistent exception on input encoding errors

- .ci/appveyor.yml
- .ci/requirements-publish.txt
- .ci/requirements-win.txt
- .ci/requirements.txt
- .ci/travis-build-docs.sh
- .ci/travis-install.sh
- .ci/travis-publish-docs.sh
- .ci/travis-release.sh
- .gitignore
- Makefile
- asyncpg/__init__.py
- docs/installation.rst
- requirements-dev.txt
- setup.py
The current setup/CI configuration has rotted a bit, especially with
respect to the control of requirements.  This is a modernization pass to
fix that and make some improvements:
1) Various requirements are now specified directly in setup.py through
"extras_require", so to install the dev dependencies it's sufficient
to run `$ pip install -e .[dev]`
2) When building or installing unreleased versions of asyncpg, the dev
version is generated automatically with setuptools_scm.
3) When cythonization is necessary, the correct version of Cython is now
used automatically through the use of setup_requires.
> Modernize and improve setup.py

- asyncpg/_testbase/__init__.py
- asyncpg/pool.py
- tests/test_pool.py
The new `Pool.cycle()` method expires all currently open connections,
so they would be replaced with fresh ones on the next `acquire()`
attempt.
The new `Pool.set_connect_args()` allows changing the connection
arguments for an existing pool instance.  Coupled with `cycle()`, it
allows adapting the pool to the new environment conditions without
having to replace the pool instance.
Fixes: #291
> Implement support for pool connection rotation

- asyncpg/connection.py
- tests/test_listeners.py
Hello. I did not open an issue for this but I included a test. Roughly, channel names are not quoted when used with `listen` and `unlisten`. This causes PostgreSQL to yell at you, and an exception to be raised by asyncpg, if they have funny characters or are not valid identifiers. Also they're case insensitive:
> Quoting an identifier also makes it case-sensitive, whereas unquoted names are always folded to lower case. For example, the identifiers FOO, foo, and "foo" are considered the same by PostgreSQL...
As a result of quoting, this diff could break some asyncpg applications that listen on `FOO` with while another application notifies on `foo` or `FOO` or `"foo"`. Previously it would see all of those notifications, now it would see none of them. However, I think the current behaviour …
> Quoting channel name in LISTEN and UNLISTEN.

- asyncpg/protocol/hton.h
`#if FOO == BAR` is true if neither BAR, nor FOO are defined, and on
BSDs machine endianness is declared as `_BYTE_ORDER`, not
`__BYTE_ORDER`, so we would compile a big-endian variant on
little-endian machines.
Fixes #313.
> Fix bswap on *BSD

- asyncpg/protocol/codecs/array.pyx
- tests/test_codecs.py
This was partially fixed in #300 (as a fix for #279), however that fix
missed the fact that OID arrays were still handled using the signed
integer codec.
Fixes: #316
> Fix handling of large type OIDs

- asyncpg/compat.py
- asyncpg/connection.py
- asyncpg/pool.py
- asyncpg/protocol/prepared_stmt.pxd
- asyncpg/protocol/prepared_stmt.pyx
- asyncpg/protocol/protocol.pxd
- asyncpg/protocol/protocol.pyx
- tests/test_connect.py
- tests/test_pool.py
Connection objects currently stay alive and open if they are not
explicitly closed or terminated.  GC won't happen to them because event
loops have a strong reference to their underlying Transport object.
By replacing a strong Connection<->Protocol reference with a weak one,
we are able to implement `Connection.__del__()` method that:
* issues a warning if a Connection object is being GCed prior
to be explicitly closed;
* terminates the underlying Protocol and Transport, effectively closing
the open network connection to the Postgres server.
When in asyncio debug mode (enabled by PYTHONASYNCIODEBUG env variable
or explicitly with `loop.set_debug(True)`) Connection objects save the
traceback of their origin and later use it to make the GC warning
clarer.
Addresses #323.
> Break strong ref between Connection and Protocol.

- asyncpg/protocol/record/recordobj.c
- docs/api/index.rst
- tests/test_record.py
`Record.get()` allows record objects to better masquerade as dicts.
Fixes: #330.
> Implement Record.get()

- asyncpg/protocol/coreproto.pxd
- asyncpg/protocol/coreproto.pyx
* Group `Bind/Execute/Sync` into one TCP packet - less traffic, faster in processing.
* Append `Sync` to a previous command packet in all flows.
* Plus save one `memcpy()` in `_prepare` as a bonus.
> Group B/E/S into one TCP packet

- asyncpg/protocol/codecs/array.pyx
- asyncpg/protocol/codecs/base.pxd
- asyncpg/protocol/codecs/base.pyx
- docs/usage.rst
- tests/test_codecs.py
This allows asyncpg to take an arbitrary mapping as input for composite
types, as long as the keys match composite type fields.
This allows removing some tedium when handling complex composite types.
Fixes: #349.
> Allow mappings as composite type input

- asyncpg/types.py
- tests/test_codecs.py
These methods assist in converting between BitStrings and ints,
which is useful when bridging between Postgres and things like
bitmasks, enum.IntFlag, etc.
> Add BitString.to_int and BitString.from_int

- asyncpg/protocol/coreproto.pxd
- asyncpg/protocol/coreproto.pyx
- asyncpg/protocol/protocol.pyx
ReadyForQuery is special in auth and simple query flows, where it _does_
signal the final confirmation of the result, but in all other flows
other, more specific messages do that.  Now, asyncpg will use the
rules of a particular subprotocol when determining the timing of the
result waiter wakeup.  These changes also make most cases of Sync
emission unnecessary, although that cleanup will be addressed in
subsequent commits.  This consolidation also results in a nice
reduction of duplicated code.
> Stop treating ReadyForQuery as a universal result indicator

- asyncpg/protocol/buffer.pxd
- asyncpg/protocol/buffer.pyx
- asyncpg/protocol/coreproto.pyx
The current ReadBuffer interface is somewhat error prone.  There is no
way to "peek" at the next message, so various subprotocols that have
nested message processing loops have to resort to the `_skip_discard`
kludge on the protocol to inform the main loop that it shouldn't skip
over to the next message because the subprotocol already read too much.
Fix this by adding a way to iterate over the messages without
over-reading, and a way to "put" a message back into the buffer when
necessary.  This also renames `has_message()` to `take_message()` to
make it clear that it changes the buffer state.
> Make ReadBuffer interface more robust

- tests/test__sourcecode.py
This way, tests won't fail if both the flake8 module and the .flake8 file are missing.
> Check for .flake8 after importing flake8

- MANIFEST.in
It is needed for running the tests.
> Include .flake8 in PyPI tarball

- docs/faq.rst
Hey folks, thanks so much for all the incredible work you've been putting into the asyncio ecosystem.
The [`databases` package](https://github.com/encode/databases) provides an SQLAlchemy Core wrapper onto a number of different async database drivers, including asyncpg. I figure it'd make sense to link out to it alongside `asyncpgsa`.
> Link to `databases` package in FAQ.

- docs/usage.rst
This merge request updates the docs to fix a minor typo in the PostgreSQL Type definition from ``timestamp with timezone`` to ``timestamp with time zone``.
While attempting to try out ``asyncpg`` I created a function to create a table. I cut and pasted PostgeSQL type definitions from the asyncpg [docs](https://magicstack.github.io/asyncpg/current/usage.html) to help define my table. When I ran the function I observed the error below.
```
asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "with"
```
PostgreSQL reported a similar issue:
```
2019-03-10 06:18:09.398 UTC [74] ERROR:  syntax error at or near "with" at character 141
2019-03-10 06:18:09.398 UTC [74] STATEMENT:  
CREATE TABLE IF NOT EXISTS messages(
id bigserial PRIMARY KEY,
timestamp timestamp with timezone,
icao …
```
> fix timezone type label in docs

- asyncpg/connection.py
- tests/test_cache_invalidation.py
If the issue #416 is actually a bug, this PR should fix it.
> Fix _StatementCache.clear() PS memory leak

- asyncpg/protocol/coreproto.pxd
- asyncpg/protocol/coreproto.pyx
- asyncpg/protocol/scram.pxd
- asyncpg/protocol/scram.pyx
- tests/test_connect.py
SCRAM-SHA-256 authentication was introduced in PostgreSQL 10 as a better way
for handling password based authentication.
This implementation follows the guidance provided in the documentation, i.e.
[https://www.postgresql.org/docs/current/sasl-authentication.html#SASL-SCRAM-SHA-256](https://www.postgresql.org/docs/current/sasl-authentication.html#SASL-SCRAM-SHA-256)
A detailed, high-level explanation for how it works is provided in the definition for the SCRAMAuthentication class.
This implementation does not support channel binding (added in PostgreSQL 11) as there is still some ongoing discussion in the community for how it should be handled.
This should satisfy the requirements for #314
> Add support for SCRAM-SHA-256 authentication.

- asyncpg/protocol/coreproto.pyx
Current implementation misuses `buffertype` argument of `PyMemoryView_GetContiguous()` function.
One must pass `PyBUF_READ` or `PyBUF_WRITE` since other options lead to assertion fire (in python debug mode).
> Fix assertion fail on copy_records_to_table

- asyncpg/connect_utils.py
- tests/test_connect.py
When a connection string component contains characters that have a
special meaning in the URI (e.g. '@' or '='), percent-encoding must be
used.  asyncpg must take care to unquote the parsed components
correctly, and it doesn't currently.
Additionally, this makes asyncpg follow the libpq's behavior of parsing
the authentication part of netloc, i.e. split on the first '@' and not
the last.
Fixes: #418
Fixes: #471
> Unquote connection string components properly

- docs/installation.rst
Because the Cython files are kept in a git submodule, you must `git clone --recurse-submodules` to be able to build from source.
> Updated documentation for building from source

- asyncpg/exceptions/_base.py
- asyncpg/protocol/coreproto.pyx
- asyncpg/protocol/protocol.pyx
This is a simple implementation of PgBouncer support for asyncpg. It doesn't have any detection features, but at least changes asyncpg behavior in such a way that using pgbouncer is possible. 
I implemented part of your suggestions as described in https://github.com/MagicStack/asyncpg/pull/348#issuecomment-416058033 , but in a simpler way. I just got rid of the explicit SYNC after a parse/describe and changed it to a FLUSH. This should work regardless of the setting of statement_cache_size and whether or not it's pgbouncer or direct postgres connection.
With this, if the user wants to use PgBouncer, he'll still have to set statement_cache_size to 0, however once he does that, everything will work as expected.
Please let me know if this solution is acceptable to merge.
> Change interaction with server to only send one SYNC message (Pgbouncer support)

- asyncpg/protocol/codecs/pgproto.pyx
- docs/usage.rst
- tests/test_codecs.py
Currently we treat values with network prefix in `inet` values
as `IPvXNetwork`, instead of `IPvXInterface` which is wrong.
Fixes: #497
> Handle IP values with prefix in "inet" type as IPvXInterface

- asyncpg/connect_utils.py
**Short summary**
I've discovered that inner coroutine passed to `asyncio.wait_for` function may not be canceled even though CancelledError is raised.
Since there is no references to protocol or transport objects – that connection will leak forever.
I've found rather dirty way to deal with it. How can it be improved?
**Detailed information can be found here:**
https://bugs.python.org/issue37658
https://github.com/MagicStack/asyncpg/issues/467
https://stackoverflow.com/questions/57163025/socket-leak-with-wait-for-in-asyncio-with-python3-6-and-python3-7
> fixes leaking connections in _connect_addr

- tests/test_codecs.py
The size of the output buffer in numeric decoder is computed incorrectly
which may lead to stack corruption or access to unitialized memory.
This also fixes incorrect rendering of trailing zeros in some cases.
Fixes: #520
Fixes: #514
> Fix errors in numeric binary decoder

- asyncpg/pool.py
I think pool documentation should recommend the safest approaches first (i.e. with the fewest possible mistakes), and discourage lower-level approach.
> Improve pool documentation examples

- asyncpg/_testbase/fuzzer.py
- asyncpg/connection.py
- tests/test_listeners.py
https://github.com/MagicStack/asyncpg/issues/421#issuecomment-475663253
- I'm not sure that the API is what I want. It's called a "cleanup listener" internally and a "close listener" externally.
- I don't know how to add tests for this.
Other than that, how does this look? The following code demonstrates the functionality. It prints True after a postgres server restart, then exits:
```py
#!/usr/bin/env python3
import asyncpg
import asyncio
async def amain():
conn = await asyncpg.connect()
cleanup_ran = False
def close_listener(_):
nonlocal cleanup_ran
cleanup_ran = True
conn.add_close_listener(close_listener)
while await asyncio.sleep(1, True):
if conn.is_closed():
print(cleanup_ran)
break
if __name__ == '__main__':
asyncio.run(amain())
```
> add support for connection closed listeners

- docs/usage.rst
Previously the usage documentation suggested that the integer values in the hstore values would be converted from strings into ints. This is not the case, as all values are returned as string or None: https://github.com/MagicStack/py-pgproto/blob/e9391d4c8615c73291bc2fc77a3e6efb484bcbd0/codecs/hstore.pyx#L66-L69
> Fix usage documentation for hstore

- .flake8
- asyncpg/_testbase/__init__.py
- asyncpg/connect_utils.py
- asyncpg/connection.py
- asyncpg/cursor.py
- asyncpg/pool.py
- asyncpg/prepared_stmt.py
- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/prepared_stmt.pxd
- asyncpg/protocol/prepared_stmt.pyx
- asyncpg/protocol/protocol.pxd
- asyncpg/protocol/protocol.pyx
- asyncpg/protocol/record/__init__.pxd
- asyncpg/protocol/record/recordobj.c
- asyncpg/protocol/record/recordobj.h
- tests/test_record.py
- tests/test_timeout.py
Add the new `record_class` parameter to the `create_pool()` and
`connect()` functions, as well as to the `cursor()`, `prepare()`,
`fetch()` and `fetchrow()` connection methods.
This not only allows adding custom functionality to the returned
objects, but also assists with typing (see #577 for discussion).
Fixes: #40.
> Allow using custom Record class

- asyncpg/protocol/record/recordobj.c
Python 3.9 moved a bunch of GC-related symbols around, including
`_PyObject_GC_IS_TRACKED` which is used in `recordobj.c`.
Fixes: #609
> Fix compilation under Python 3.9+

- asyncpg/compat.py
- asyncpg/connect_utils.py
- asyncpg/pool.py
- tests/test_pool.py
`asyncio.wait_for()` currently has a bug where it raises a
`CancelledError` even when the wrapped awaitable has completed.
The upstream fix is in python/cpython#21894.  This adds a workaround
until the aforementioned PR is merged, backported and released.
Co-authored-by: Adam Liddell <git@aliddell.com>
Fixes: #467
Fixes: #547
Related: #468
Supersedes: #548
> Add a workaround for bpo-37658

- asyncpg/connection.py
- asyncpg/transaction.py
- tests/test_transaction.py
This fixes the issue when the default_transaction_isolation is not "read committed", `transaction(isolation='read_committed')` won't start a transaction in "read committed" isolation level.
There're 2 ways to configure a different default transaction isolation level:
1. `SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL serializable;`. This SQL changes the `default_transaction_isolation` setting, and updates the default transaction isolation level too.
2. Set `default_transaction_isolation` in `postgresql.conf`. This is the server-wide default, most servers keep the default `read committed` value.
| server default | isolation parameter | before PR | after PR |
|---|---|---|---|
| read committed | not set | read committed | read committed |
| read committed | read committed | read …
> Fix wrong default transaction isolation level

- asyncpg/connection.py
- asyncpg/introspection.py
- asyncpg/protocol/__init__.py
- asyncpg/protocol/pgtypes.pxi
- tests/test_codecs.py
Currently, `Connection.set_type_codec()` only accepts type names as they
appear in `pg_catalog.pg_type` and would refuse to handle a standard SQL
spelling of a type like `character varying`.  This is an oversight, as
the internal type names aren't really supposed to be treated as public
Postgres API.  Additionally, for historical reasons, Postgres has a
single-byte `"char"` type, which is distinct from both `varchar` and
SQL `char`, which may lead to massive confusion if a user sets up a
custom codec on it expecting to handle the `char(n)` type instead.
Issue: #617.
> Fix set_type_codec() to accept standard SQL type names

- asyncpg/connection.py
- asyncpg/protocol/codecs/base.pxd
- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/prepared_stmt.pxd
- asyncpg/protocol/prepared_stmt.pyx
- asyncpg/protocol/protocol.pyx
- asyncpg/protocol/settings.pxd
- asyncpg/protocol/settings.pyx
- tests/test_introspection.py
Custom data codec may manipulate the query parameters and results, breaking the assumption of internal introspection queries. This PR disables custom data codecs for internal introspections.
Fixes: #617
> Ignore custom data codec for internal introspection

- asyncpg/protocol/codecs/array.pyx
- tests/test_codecs.py
When given a textual json codec that yields `'null'`, the array encoder should generate `b'["null"]'` instead of `b'["NULL"]'` for a `JSON[]` type.
Refs: #623
> Fix null/NULL quoting in array text encoder

- asyncpg/connection.py
Until now the url had a space in it which means the link was to 
https://www.postgresql.org/docs/current/%20libpq-connect.html#LIBPQ-CONNSTRING
which shows a 404.
see https://magicstack.github.io/asyncpg/current/api/index.html
This should fix it.
> fix link in connect docstring

- asyncpg/protocol/settings.pyx
* **asyncpg version**: 0.20.1
* **PostgreSQL version**: BDR 11.X
* **Do you use a PostgreSQL SaaS?  If so, which?  Can you reproduce
the issue with a local PostgreSQL install?**: No SaaS, local BDR
* **Python version**: 3.5.7
* **Platform**: RH Linux
* **Do you use pgbouncer?**: Yes
* **Did you install asyncpg with pip?**: Yes - but custom built
* **If you built asyncpg locally, which version of Cython did you use?**: 0.29.14
* **Can the issue be reproduced under both asyncio and
[uvloop](https://github.com/magicstack/uvloop)?**: Unknown
Executing the following code results in `AttributeError` exception - '`object`' has no attribute '`__getattr__`'
```
conn = await asyncpg.connect(dsn=...)
settings = conn.get_settings()
print(settings._settings)
```
I believe the function should be …
> Fix AttributeError exception

- asyncpg/exceptions/_base.py
- asyncpg/protocol/codecs/record.pyx
- asyncpg/protocol/prepared_stmt.pyx
- tests/test_codecs.py
Currently asyncpg would crash with an arcane "could not resolve query
result and/or argument types in 6 attempts", which isn't helpful.  Do
the right thing by raising an `UnsupportedClientFeatureError`
explicitly instead.
Fixes #476.
> Raise proper error on anonymous composite input (tuple arguments)

- asyncpg/connect_utils.py
- asyncpg/connection.py
- tests/test_connect.py
Switch the default SSL mode from 'disabled' to 'prefer'.  This matches libpq's behavior and is a sensible thing to do.
Fixes: #654
> Prefer SSL connections by default

- asyncpg/protocol/codecs/pgproto.pyx
- asyncpg/protocol/pgtypes.pxi
- tests/test_codecs.py
- tools/generate_type_map.py
The last round of support for esoteric builtin types was quite a while
ago, so catch up.  Out of non-internal types this adds support for the
new `jsonpath` type.
Fixes: #635.
> Add codecs for a bunch of new builtin types

- asyncpg/connection.py
- asyncpg/exceptions/_base.py
- asyncpg/introspection.py
- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/codecs/record.pyx
- asyncpg/protocol/prepared_stmt.pyx
- tests/test_codecs.py
Postgres always includes the base type OID in the RowDescription message
even if the query is technically returning domain values.  This makes
custom codecs on domains ineffective, and so prohibit them to avoid
confusion and bug reports.
See postgres/postgres@d9b679c and
https://postgr.es/m/27307.1047485980%40sss.pgh.pa.us for context.
Fixes: #457.
> Prohibit custom codecs on domains

- asyncpg/connection.py
- asyncpg/introspection.py
- asyncpg/protocol/codecs/base.pxd
- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/settings.pyx
- tests/test_codecs.py
Asyncpg currently erroneously prefers binary I/O for underlying type of
arrays effectively ignoring a possible custom text codec that might have
been configured on a type.
Fix this by removing the explicit preference for binary I/O, so that the
codec selection preference is now in the following order:
- custom binary codec
- custom text codec
- builtin binary codec
- builtin text codec
Fixes: #590
Reported-by: @neumond
> Untangle custom codec confusion

- asyncpg/connection.py
- asyncpg/protocol/record/recordobj.c
- asyncpg/protocol/record/recordobj.h
- tests/test_record.py
The current implementation has a bunch of `CheckExact` calls in front of
most `Record` methods, effectively making them unusable in subclasses.
Relax the check to include the subclasses.
While at it, add a check that `__init__` and `__new__` are not redefined
on the provided Record subclass.  Doing so is pointless, because
`Record` instance initialization effectively bypasses both, so raise an
`InterfaceError` to avoid needless confusion.
Fixes: #676
> Fix method calls on custom Record subclasses

- asyncpg/connection.py
There's no need to unlisten on all channels if there are no active listeners on the connection. Querying `pg_listening_channels` could be quite time consuming even when no listeners are added. For example, 20% of all time spent on DB operations goes to `pg_listening_channels` on our project.
> Avoid unnecessary pg_listening_channels queries on connection release

- asyncpg/connection.py
There is a small typo in asyncpg/connection.py.
Should read `verification` rather than `verifiction`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, verifiction -> verification

- .github/workflows/release.yml
- asyncpg/_version.py
A new asyncpg release is here.
Notable additions include Python 3.9 support, support for recently added
PostgreSQL types like `jsonpath`, and last but not least, vastly
improved `executemany()` performance.  Importantly, `executemany()` is
also now _atomic_, which means that either all iterations succeed, or
none at all, whereas previously partial results would have remained in
place, unless `executemany()` was called in a transaction.
There is also the usual assortment of improvements and bugfixes, see the
details below.
This is the last release of asyncpg that supports Python 3.5, which has
reached EOL last September.
Improvements
------------
* Vastly speedup executemany by batching protocol messages (#295)
(by @fantix in 690048db for #295)
* Allow using custom `Record` class
(by …
> asyncpg v0.22.0

- asyncpg/transaction.py
> Avoid TypeError in Transaction.__repr__

- asyncpg/protocol/coreproto.pyx
- tests/test_connect.py
This fixes an issue in 0.22.0 where we passed WriteBuffer to writelines by mistake, which leads to an error under SSL and uvloop - the implementation that calls len() on each line of writelines().
Fixes: #700
> Feed memoryview to writelines()

- docs/index.rst
The README.md says that PostgreSQL versions supported are 9.5 to 13,
copied to the doc.
> Updated int the doc PostgreSQL versions supported

- .github/workflows/tests.yml
Python 3.5 on GitHub Action ran into some certificate issue that newer version of pip doesn't have, so upgrading to the latest by default.
> Upgrade pip and setuptools in workflow

- asyncpg/connect_utils.py
- asyncpg/connection.py
- asyncpg/protocol/protocol.pxd
- asyncpg/protocol/protocol.pyx
- tests/test_connect.py
We didn't really retry the connection without SSL if the first SSL connection fails under `sslmode=prefer`, that led to an issue when the server has SSL support but explicitly denies SSL connection through `pg_hba.conf`. This commit adds a retry in a new connection, which makes it easy to implement the `sslmode=allow` retry.
Fixes #716
> Add sslmode=allow support and fix =prefer retry

- .github/workflows/tests.yml
Due to executable file locking `pip install -U pip` doesn't work on
Windows, one has to use `python -m pip install -U pip` instead.
> Fix CI on Windows

- tests/test_codecs.py
In test_invalid_input, also accept “(str object cannot be interpreted as an integer)” wherever we expected “an integer is required”; required for Python 3.10 compatibility. This fixes https://github.com/MagicStack/asyncpg/issues/750.
> Loosen message test in test_invalid_input

- asyncpg/transaction.py
> Support readonly and deferrable for non-serializable transactions

- asyncpg/connect_utils.py
Copied from edgedb/edgedb#2398
> Rename _Retry to _RetryConnectSignal

- asyncpg/protocol/record/recordobj.c
If Py_DEBUG enabled, then newly allocated memory is filled with the byte 0xCD (CLEANBYTE) https://docs.python.org/3/c-api/memory.html#c.PyMem_SetupDebugHooks
This breaks checks for `pointer == NULL` and results in crash.
From documentation PyObject_GC_Track https://docs.python.org/3/c-api/gcsupport.html#c.PyObject_GC_Track
> This should be called once all the fields followed by the tp_traverse handler become valid, usually near the end of the constructor.
> Fix asyncpg with Py_DEBUG mode

- MANIFEST.in
Add patterns matching them to `MANIFEST.in`.
> Fix docs/Makefile and docs/_static/theme_overrides.css missing from PyPI package

- asyncpg/_version.py
Fixes
-----
* Avoid TypeError in `Transaction.__repr__` (#703)
(by @BeatButton in d6eea8ed for #703)
* Feed memoryview to `writelines()` (#715)
(by @fantix in 359a34c4 for #715)
* Add sslmode=allow support and fix =prefer retry (#720)
(by @fantix in 075114c1 for #720)
* Loosen message test in `test_invalid_input` (#751)
(by @musicinmybrain in bc4127f4 for #751)
* Support readonly and deferrable for non-serializable transactions (#747)
(by @pauldraper in 5cf4089a for #747)
* Fix asyncpg with `Py_DEBUG` mode (#719)
(by @shadchin in a113d908 for #719)
* Fix docs/Makefile and docs/_static/theme_overrides.css missing from PyPI package (#708)
(by @musicinmybrain in c3060680 for #708)
> asyncpg v0.23.0

- asyncpg/connect_utils.py
- asyncpg/connection.py
- tests/test_connect.py
The connection will now terminate itself immediately if there is no external reference to it.
Refs #772
> Break connection internal circular reference

- .github/workflows/release.yml
- .github/workflows/tests.yml
- README.rst
- asyncpg/compat.py
- asyncpg/connection.py
- asyncpg/cursor.py
- docs/index.rst
- setup.py
- tests/test_copy.py
This PR is just an excerpt from #577. The goal is to merge #577 as soon as possible but it's so huge that it's difficult to approach it. Let's try to merge it step by step.
Thanks for the original work @bryanforbes!
> Drop support for Python 3.5

- asyncpg/serverversion.py
- tests/test_connect.py
https://github.com/MagicStack/asyncpg/issues/250
https://github.com/MagicStack/asyncpg/issues/261
https://github.com/MagicStack/asyncpg/issues/771
Just tried to use this library through Ormar->Databases->AsyncPG against
a Yugabyte cluster and hit issue 771. Looks like this has been a problem
for a while now so going for a complete overhaul of the server version
extraction method. Using a groupdict regex against the version string
allows for much higher flexibility in extracting what we're looking for
and fixes 771 while not breaking any of the existing version patterns.
> Make Server Version Extraction More Flexible

- setup.py
0.29.24 is needed to compile properly under Python 3.10
> Bump minimum required Cython version

- asyncpg/connection.py
- asyncpg/protocol/protocol.pyx
- tests/test_copy.py
The `Connection.copy_records_to_table()` now allows the `records`
argument to be an asynchronous iterable.
Fixes: #689.
> Add support for asynchronous iterables to copy_records_to_table()

- asyncpg/connection.py
- tests/test_listeners.py
The `Connection.add_listener()`, `Connection.add_log_listener()` and
`Connection.add_termination_listener()` now allow coroutine functions as
callbacks.
Fixes: #567.
> Add support for coroutine functions as listener callbacks

- .github/workflows/release.yml
- .github/workflows/tests.yml
Bump versions of various actions used in the workflow, add Python 3.10
to the release list and silence pointless pip warnings which get
surfaced as error annotations.
> Github workflows touchups

- asyncpg/_version.py
Changes
-------
* Drop support for Python 3.5 (#777)
(by @and-semakin in da58cd26 for #777)
* Add support for Python 3.10 (#795)
(by @elprans in abf55699 for #795)
* Add support for asynchronous iterables to `copy_records_to_table()` (#713)
(by @elprans in 1d33ff62 for #713)
* Add support for coroutine functions as listener callbacks (#802)
(by @elprans in 41da093e for #802)
* Add support for sslcert, sslkey and sslrootcert parameters to DSN (#768)
(by @jdobes and @elprans in c674e86a for #768)
* Add copy_ wrappers to Pool (#661)
(by @elprans in a6b0f283 for #661)
* Add issubset and issuperset methods to the Range type (#563)
(by @kdorsel in de07d0ab for #563)
Fixes
-----
* Break connection internal circular reference (#774)
(by @fantix in d08a9b8b for #774)
* Make Server Version …
> asyncpg v0.24.0

- asyncpg/protocol/protocol.pyx
Under certain circumstances the `TimerHandle` used for query timeouts
does not get cleaned up in a timely fashion resulting in a temporary
(`timeout` seconds) memory leak.
Fixes: #830
> Make sure timeout callbacks always get cleaned up

- asyncpg/pool.py
- tests/test_pool.py
The new `Pool.get_size()`, `Pool.get_min_size()`, `Pool.get_max_size()`,
`Pool.get_idle_size()` methods are added to get the size of the current,
minimum, maximum and idle connection set size at any given moment.
> Add Pool methods to determine its min, max, current and idle size

- asyncpg/connection.py
The docs incorrectly claim that the `database` argument defaults to
the OS username, whereas in fact, the computed value of the `user`
argument is used.
Fixes: #823.
> Fix the description of the database argument to connect()

- asyncpg/connection.py
- asyncpg/prepared_stmt.py
- tests/test_prepare.py
This adds the new `name` keyword argument to `Connection.prepare()` and
`PreparedStatement.get_name()` method returning the name of a statement.
Some users of asyncpg might find it useful to be able to control how
prepared statements are named, especially when a custom prepared
statement caching scheme is in use.  Specifically, This should help with
pgbouncer support in SQLAlchemy asyncpg dialect.
Fixes: #837.
> Make it possible to specify a statement name in Connection.prepare()

- asyncpg/connect_utils.py
- asyncpg/connection.py
- tests/test_connect.py
Plain IPv6 addresses specified in square brackets in the connection URI
are now parsed correctly.
Fixes: #838.
> Fix parsing of IPv6 addresses in the connection URI

- asyncpg/protocol/prepared_stmt.pxd
- asyncpg/protocol/prepared_stmt.pyx
- asyncpg/protocol/protocol.pyx
- tests/test_execute.py
This adds a check that elements of sequence passed to `executemany()`
are proper sequences themselves and notes the offending sequence element
number in the exception message.  For example:
await self.con.executemany(
"INSERT INTO exmany (b) VALUES($1)"
[(0,), ("bad",)],
)
DataError: invalid input for query argument $1 in element #1 of
executemany() sequence: 'bad' ('str' object cannot be
interpreted as an integer)
Fixes: #807
> Improve diagnostics of invalid executemany() input

- .github/workflows/install-postgres.sh
- .github/workflows/release.yml
- Makefile
- asyncpg/_version.py
- asyncpg/protocol/codecs/range.pyx
- asyncpg/protocol/prepared_stmt.pyx
- asyncpg/protocol/protocol.pyx
- asyncpg/protocol/record/recordobj.c
- pyproject.toml
- setup.py
- tests/__init__.py
- tests/test_connect.py
Changes
-------
* Improve SSL option compatibility in URIs
(by @fantix in 383c711e for #827)
* Add `Pool` methods to determine its min, max, current and idle size
(by @elprans in 603e3868 for #849)
* Make it possible to specify a statement name in `Connection.prepare()`
(by @elprans in 03a3d18f for #846)
* Implement support for `multirange` types
(by @elprans in d64a44a1 for #851)
Fixes
-----
* Make sure timeout callbacks always get cleaned up
(by @elprans in dad26913 for #831)
* Update `__all__` statements to a simpler form that is better supported by typecheckers
(by @bschnurr in 0a3ae7f5 for #828)
* Fix `test_timetz_encoding` on Python 3.10
(by @elprans in 3a90fef0)
* Fix a bunch of `ResourceWarnings` in the test suite
(by @elprans in 2f4fe539)
* Fix `SSLContext` deprecation warnings …
> asyncpg v0.25.0

- pyproject.toml
> Fix invalid `pyproject.toml`

- asyncpg/pool.py
I guess these functions are supposed to have the same signature as their counterpart in `Connection`
> Add record_class parameter Pool.fetch and Pool.fetchrow

- asyncpg/introspection.py
- tests/test_introspection.py
Domain encoding/decoding is handled by its basetype. This change forces
those basetypes to be inspected and loaded to the client cache avoiding
the issue where base types weren't encodable/decodable.
> Domain basetypes are introspected (#886)

- asyncpg/connect_utils.py
- tests/test_connect.py
This will allow to pass lambda or `functools.partial` that returns `Future`.
> Add support to use awaitable object in password function.  

- asyncpg/protocol/coreproto.pyx
- tests/test_connect.py
When server sends us an authentication request message and we fail to
process it, we must terminate the connection and propagate the exception
immediately.  Currently asyncpg will just timeout waiting for
`ReadyForQuery` from the server, which will never arrive.
Fixes: #861
> Properly handle exceptions raised while handling server auth messages

- asyncpg/connect_utils.py
- asyncpg/connection.py
- tests/test_connect.py
Adding `direct_tls` param that when equal to `True` alongside the `ssl` param being set to a `ssl.SSLContext` will result in a direct SSL connection being made, skipping STARTTLS implementation.
Closes #906
> feat: allow direct SSL connection over STARTTLS

- .github/workflows/install-postgres.sh
- .github/workflows/release.yml
- tests/test_introspection.py
Fixes #870 
Fixes #936 
Fixes #950
This PR:
- Adds a fair amount of parallellization ref https://github.com/pypa/cibuildwheel/issues/1088#issuecomment-1250024795
- Uses latest manylinux images (RHEL8.6) for building future-proof wheels: the default yum repo comes with pg10 (left it like that for simplicity in the install script)
- Automatically determines which python versions to build wheels for based on `setup.py`
- Avoids prematurely publishing new docs when building wheels could still fail
> Add arm64 mac and linux wheels

- .flake8
Virtual environment directories are often named `.venv` by convention.
> Exclude .venv from flake8

- setup.py
This moves the project to a more modern version of flake8 (and its dependencies). No new lint issues were identified by this upgrade.
> Upgrade to flake8 5.0.4 (from 3.9.2)

- docs/faq.rst
This demonstrates a dot-notation implementation as suggested by this
FAQ item.
> Show an example of a custom Record class

- asyncpg/protocol/record/recordobj.c
- tests/test_record.py
We support `Record` subclasses, so include the exact type name
(rather than just `'Record'`) in the `repr()` string.
> Use the exact type name in Record.__repr__

- .github/workflows/tests.yml
- README.rst
- asyncpg/compat.py
- asyncpg/connect_utils.py
- asyncpg/connection.py
- asyncpg/pool.py
- asyncpg/protocol/scram.pyx
- docs/index.rst
- setup.py
- tests/test_connect.py
- tests/test_pool.py
Python 3.6 reached end-of-life [back in December](https://peps.python.org/pep-0494/#lifespan). Since 0.26.0 was just released with support for 3.6, the next release should probably drop support for it.
> Drop Python 3.6 support

- asyncpg/_version.py
Support Python 3.11 and PostgreSQL 15.  This release also drops support
for Python 3.6.
Changes
=======
* Add arm64 mac and linux wheels
(by @ddelange in 7bd6c49f for #954)
* Add Python 3.11 to the test matrix
(by @elprans in 5f908e67 for #948)
* Exclude .venv from flake8 (#958)
(by @jparise in 40b16ea6 for #958)
* Upgrade to flake8 5.0.4 (from 3.9.2) (#961)
(by @jparise in 0e73fec2 for #961)
* Show an example of a custom Record class (#960)
(by @jparise in 84c99bfd for #960)
* Use the exact type name in Record.__repr__ (#959)
(by @jparise in eccdf61a for #959)
* Drop Python 3.6 support (#940)
(by @bryanforbes in bb0cb39d for #940)
* Test on Python 3.11 and PostgreSQL 15, fix workflow deprecations (#968)
(by @elprans in eab7fdf2 for #968)
> asyncpg v0.27.0

- asyncpg/connection.py
This supports a case where we prepare an unnamed statement to inspect the return types. The statement should not be cleaned up afterwards because it is automatically cleaned up by Postgres
Fixes: #982
> Do not try to cleanup anonymous statements

- asyncpg/pool.py
- tests/test_pool.py
Sometimes, application code wants to check if a `Pool` is still open or not. This adds an `is_closing()` method to the public API for `Pool`, so that it's easy to do so.
> Add Pool.is_closing() method

- .github/workflows/release.yml
fix for #954 xref https://github.com/pypa/cibuildwheel/discussions/1261#discussioncomment-4734606
e.g. `cp36-manylinux_x86_64` was missing on pypi, because the first line was swallowed when using `inputs`:
```console
$ cibuildwheel --print-build-identifiers --platform linux --arch x86_64,aarch64 | grep cp |  jq -nRc '{"only": inputs, "os": "ubuntu-latest"}'
{"only":"cp36-manylinux_x86_64","os":"ubuntu-latest"}
{"only":"cp37-manylinux_x86_64","os":"ubuntu-latest"}
{"only":"cp38-manylinux_x86_64","os":"ubuntu-latest"}
{"only":"cp39-manylinux_x86_64","os":"ubuntu-latest"}
{"only":"cp310-manylinux_x86_64","os":"ubuntu-latest"}
{"only":"cp311-manylinux_x86_64","os":"ubuntu-latest"}
{"only":"cp36-manylinux_aarch64","os":"ubuntu-latest"}
{"only":"cp37-manylinux_aarch64","os":"ubuntu-latest"} …
```
> Fix missing PyPI wheels

- asyncpg/compat.py
- asyncpg/connect_utils.py
- tests/test_connect.py
Certain environments don't have a home directory, such as systemd services with `DynamicUser=yes`. This adds error handling when connecting in such cases.
> Handle environments without home dir

- asyncpg/connection.py
- asyncpg/transaction.py
- tests/test_transaction.py
Add support for "READ UNCOMMITTED" transaction isolation level.
This transaction isolation level can be useful for testing, and is [supported by PostgreSQL](https://www.postgresql.org/docs/current/sql-set-transaction.html).
> Add support for READ UNCOMMITTED

- .github/workflows/release.yml
- Makefile
- asyncpg/connection.py
- docs/conf.py
- docs/index.rst
- pyproject.toml
- setup.py
> Move most metadata to pyproject.toml

- asyncpg/connect_utils.py
`asyncio.gather` takes a variadic, not an iterable and
`return_exceptions` was masking the issue.
> Fix closing of connection discarded by session target attrs

- pyproject.toml
Looks like later versions dropped Python 3.7 support
> Scale flake8 back to 5.0

- .flake8
- .github/workflows/tests.yml
- README.rst
- docs/index.rst
- pyproject.toml
- setup.py
- tests/test_adversity.py
- tests/test_listeners.py
Since Python 3.7 is EOL, it would be good to drop it from the next release
> Drop support for Python 3.7

- asyncpg/connect_utils.py
- asyncpg/exceptions/_base.py
- tests/test_connect.py
If `HOME` points to a regular file (or `/dev/null`), make sure we don't
crash unnecessarily, and if we do need to crash, so so informatively.
Fixes: #1014
> Handle environments with HOME set to a not-a-directory

- asyncpg/connection.py
- asyncpg/introspection.py
- asyncpg/protocol/codecs/base.pxd
- asyncpg/protocol/codecs/base.pyx
- asyncpg/protocol/settings.pxd
- asyncpg/protocol/settings.pyx
- docs/usage.rst
- tests/test_codecs.py
It is now possible to `set_type_codec('mycomposite', ... format='tuple')`,
which is useful for types that are represented by a composite type in
Postgres, but are an integral type in Python, e.g. `complex`.
Fixes: #1060
> Add support for tuple-format custom codecs on composite types

- asyncpg/protocol/coreproto.pyx
- tests/test_connect.py
> Fix handling of non-ASCII passwords

- asyncpg/connection.py
- tests/test_introspection.py
The misapplication of JIT to asyncpg introspection queries has been a
constant source of user complaints.
Closes: #530
Closes: #1078
Previously: #875, #794, #782, #741, #727 (and probably more).
> Disable JIT while doing type introspection

- tests/test_codecs.py
> Issue #1020 Infinity numeric support

- asyncpg/pool.py
- tests/test_pool.py
Now when using target_session_attrs, for example "primary" and if the leader in the cluster changes - the connections continue to open to the replica.
Since the server role check is performed only at the first connection and all information for further connections is cached in `Pool._working_*`.
This PR proposes to add server role checking on every connection when using target_session_attrs and if the server role does not match the one specified in target_session_attrs, clear the `Pool._working_*` cache.
The impact on performance is minimal and will only be if target_session_attrs is used.
Without these changes target_session_attrs becomes useless, as it really works only at application startup.
> Reconnect when server role changed

- asyncpg/_asyncio_compat.py
- asyncpg/compat.py
- asyncpg/protocol/protocol.pyx
- pyproject.toml
`wait_for` has been a mess with respect to cancellations
consistently in `asyncio`.  Hopefully the approach taken in
Python 3.12 solves the issues, so adopt that instead of trying
to "fix" `wait_for` with wrappers on older Pythons.  Use `async_timeout`
as a polyfill on pre-3.11 Python.
Closes: #1056
Closes: #1052
Fixes: #955
> Switch to Python 3.12-style `wait_for`

- docs/usage.rst
Shapely 1.8/2.0 depreciates the `shapely.geometry.asShape()` method in favor of `shapely.geometry.shape()` [source](https://shapely.readthedocs.io/en/stable/migration.html#other-deprecated-functionality).
Small change, but could save someone my headache.
> Update automatic PostGIS automatic type conversion example for Shapely 1.8/2.0

- asyncpg/compat.py
- asyncpg/connect_utils.py
- asyncpg/connection.py
- tests/test_adversity.py
- tests/test_connect.py
Drop timeout management gymnastics from the `connect()` path and use the
`timeout` context manager instead.
> Use the `timeout` context manager in the connection path

- docs/usage.rst
The original example causes issues when I try to write tests with `pytest`. Database initialization and aiohttp runtime have different loops. Also, there is no code that closes all connections in the pool after usage.   
The provided example resolves these issues.
> Update example of pool usage with aiohttp

- asyncpg/connection.py
- asyncpg/exceptions/_base.py
- asyncpg/pool.py
- tests/test_copy.py
Hi there,
This PR closes issue #939, and adds support for a `where` parameter in the `copy_to` family of methods. It is not a breaking change and will not affect existing code. Apologies for the delay - work has been pretty crazy the past couple days.
There are a couple things I'm unsure of here and wanted to flag:
- Is the addition of `UnsupportedServerFeatureError` warranted? The existing exception types didn't seem like a good fit, but maybe this is too much of a special case to warrant its own.
- Is raising an exception the desired behavior on unsupported Postgres versions? I don't really see a reasonable way to "backport" this behavior in order to avoid an exception, but maybe I'm missing something.
- There _is_ the option of issuing a warning instead, and allowing the inevitable …
> Add support for `WHERE` clause in `copy_to` methods

- asyncpg/cursor.py
- asyncpg/protocol/protocol.pyx
- tests/test_cursor.py
When iterating on a cursor, make sure to close the portal once iteration
is done.  This prevents the cursor from holding onto resources until the
end of transaction.
Fixes: #1008
> Close cursor portals once the iterator is exhausted

- asyncpg/protocol/protocol.pxd
- asyncpg/protocol/protocol.pyx
- tests/test_connect.py
A bound method contains a reference to the instance it's bound to. Most of the time, bound methods are created lazily at access time by the descriptor protocol and discarded after calling. But saving a bound method as another attribute on the instance creates a long-lived cycle, here `.timeout_callback.__self__`, that needs to be explicitly broken if we don't want to wake up python's garbage collector to do it.
Without this change, the new assertion in the tests would fail, and `pytest --pdb` would show the bound methods `_on_timeout` and `_on_waiter_completed` at the end of `p gc.get_referrers(protoref())`.
Things I'm not too certain about:
- whether I got all of the codepaths that need to delete `.timeout_callback` and `.completed_callback`—I empirically seem to have covered my use …
> Cut BaseProtocol circular reference on close.

- .github/release_log.py
- .github/workflows/release.yml
- asyncpg/_version.py
Minor fixes and improvements.
Improvements
============
* Python 3.12 and PostgreSQL 16 support (#1084)
(by @elprans in deea86ce)
* Add support for tuple-format custom codecs on composite types (#1061)
(by @elprans in 922fcd10)
* Support `target_session_attrs` in URL format, add tests (#1073)
(by @elprans in 7cb4e70d)
* Infinity numeric support (#1067)
(by @krokoziabla in 0c3bf600 for #1020)
* Add support for the `WHERE` clause in `copy_to` methods (#941)
(by @kaylynn234 in b7ffab6c)
* Add query logging callbacks and context manager (#1043)
(by @dcwatson in b2697ffd)
Fixes
=====
* When prepared statements are disabled, avoid relying on them harder (#1065)
(by @elprans in cbf64e18)
* Handle environments with HOME set to a not-a-directory (#1063)
(by @elprans in af922bcf)
* Fix handling of …
> asyncpg v0.29.0

- .github/workflows/install-krb5.sh
- .github/workflows/tests.yml
- asyncpg/connect_utils.py
- asyncpg/connection.py
- asyncpg/protocol/coreproto.pxd
- asyncpg/protocol/coreproto.pyx
- asyncpg/protocol/protocol.pxd
- asyncpg/protocol/protocol.pyx
- pyproject.toml
- tests/test_connect.py
Most commonly used with Kerberos.
Closes: #769
> Implement GSSAPI authentication

- .flake8
- .github/workflows/release.yml
- .gitignore
- MANIFEST.in
- asyncpg/__init__.py
- asyncpg/_asyncio_compat.py
- asyncpg/_version.py
- asyncpg/compat.py
- asyncpg/introspection.py
- asyncpg/protocol/__init__.py
- asyncpg/protocol/protocol.pyi
- asyncpg/serverversion.py
- asyncpg/types.py
- pyproject.toml
- setup.py
- tests/test__sourcecode.py
* Added typings to miscellaneous files
* Added unit test to check codebase with mypy
* Updated release workflow and build to account for annotations
* Updated manifest to include stub files
> Add initial typings

- README.rst
- asyncpg/connect_utils.py
- asyncpg/connection.py
- asyncpg/protocol/coreproto.pxd
- asyncpg/protocol/coreproto.pyx
- docs/installation.rst
- pyproject.toml
- tests/test_connect.py
SSPI is a Windows technology for secure authentication. SSPI and GSSAPI interoperate as clients and servers. Postgres documentation recommends using SSPI on Windows clients and servers and GSSAPI on non-Windows platforms[1].
Changes in this PR:
* Support AUTH_REQUIRED_SSPI server request. This is the same as AUTH_REQUIRED_GSS, except it allows negotiation with SSPI clients.
* Allow using SSPI on the client. Which library to use can be specified using the `gsslib` connection parameter.
* Use SSPI instead of GSSAPI on Windows by default. The latter requires installing Kerberos for Windows and is unlikely to work out of the box.
Closes #142
[1] https://www.postgresql.org/docs/current/sspi-auth.html
> Implement SSPI authentication

- README.rst
- asyncpg/connection.py
- docs/api/index.rst
- docs/usage.rst
- tools/generate_type_map.py
> Use asyncio.run() instead of run_until_complete()

- .github/workflows/tests.yml
It appears that Github no longer preinstalls Postgres in their default
runner images, so do this explicitly.
> .github: Explicitly install Postgres in platform tests

- asyncpg/compat.py
- asyncpg/pool.py
Use `markcoroutinefunction` (available in Python 3.12+) to make
`inspect.iscoroutinefunction()` return the correct answer for wrapped
connection methods.
Fixes: #1133
> Mark pool-wrapped connection coroutine methods as coroutines

- pyproject.toml
- setup.py
This simply loosens the version upper bounds to `<4.0.0`.
> Allow Cython 3 (fix #1083)

- asyncpg/pool.py
In situations where the pool is awaited multiple times, `None` is returned after the initial `await`. To fix this, the pool is returned from `_async_init__` when the pool is already initialized and not just after the first initialization.
> fix: return the pool from _async_init__ if it's already initialized

- asyncpg/protocol/record/recordobj.c
Use `Py_TRASHCAN_BEGIN`/`END` instead.
https://bugs.python.org/issue44874
These are removed from the limited C API in Python 3.9, deprecated in 3.11, and removed in Python 3.13:
https://docs.python.org/3.13/whatsnew/3.13.html#id8
> Replace obsolete, unsafe Py_TRASHCAN_SAFE_BEGIN/END

- asyncpg/protocol/coreproto.pxd
- asyncpg/protocol/coreproto.pyx
This is used by libpq and allows us to skip canonicalization of host name, which was making a blocking DNS lookup.
Similarly, don't canonicalize host name for SSPI, since this is not done by libpq.
> gssapi: use hostbased_service name type

- .github/workflows/tests.yml
- pyproject.toml
There have been binary wheels for uvloop for Python 3.12 for some time.
> Allow testing with uvloop on Python 3.12

- pyproject.toml
Hello,
It looks like `async_timeout` might only be installed for python < 3.11.
This was initially added in #1086 as part of the switch to the updated in python 3.12 `asyncio.wait_for`, however `asyncio.timeout` is available starting from 3.11.
> Require async_timeout for python < 3.11

- asyncpg/prepared_stmt.py
- asyncpg/protocol/prepared_stmt.pyx
- tests/test_exceptions.py
it is available in Postgres since version 15
> notice also the MERGE command

- asyncpg/utils.py
- tests/test_copy.py
When a parameter to a query is of `NoneType` it should populate with `NULL` in the query, it was currently leaving an empty space.
> handle `None` parameters in query, returning NULL

- asyncpg/_testbase/__init__.py
The proactor stuff on Windows raises a spurious `ConnectionResetError`
while trying to shut down a socket in the `connection_lost` path.  This
is likely a Python bug (and nobody noticed because this is a background
exception).  Try to filter it out before complaining.
> tests: Attempt to inhibit spurious ConnectionResetError on Windows

- asyncpg/connection.py
- asyncpg/pool.py
- asyncpg/prepared_stmt.py
- asyncpg/protocol/coreproto.pxd
- asyncpg/protocol/coreproto.pyx
- asyncpg/protocol/protocol.pyx
- tests/test_execute.py
- tests/test_prepare.py
Fixes #448
This change adds a `fetchmany` method to `Pool`, `Connection`, and `PreparedStatement` which allows you execute `INSERT ... RETURNING` with a list of values and get the result.
> Add `fetchmany` to execute many *and* return rows

- asyncpg/connection.py
- asyncpg/pool.py
- tests/test_pool.py
A coroutine can be passed to the new `reset` argument of `create_pool`
to control what happens to the connection when it is returned back to
the pool by `release()`.  By default `Connection.reset()` is called.
Additionally, `Connection.get_reset_query` is renamed from
`Connection._get_reset_query` to enable an alternative way of
customizing the reset process via subclassing.
Closes: #780
Closes: #1146
> Allow customizing connection state reset

- .github/workflows/install-krb5.sh
- .github/workflows/install-postgres.sh
- .github/workflows/release.yml
- .github/workflows/tests.yml
- asyncpg/_testbase/__init__.py
- asyncpg/_version.py
- asyncpg/cluster.py
- pyproject.toml
- tests/test_connect.py
Support Python 3.13 and PostgreSQL 17.
Improvements
============
* Implement GSSAPI authentication
(by @eltoder in 1d4e5680 for #1122)
* Implement SSPI authentication
(by @eltoder in 1aab2094 for #1128)
* Add initial typings
(by @bryanforbes in d42432bf for #1127)
* Allow building with Cython 3
(by @musicinmybrain in 258d8a95 for #1101)
* docs: fix connection pool close call (#1125)
(by @paulovitorweb in e8488149 for #1125)
* Add support for the `sslnegotiation` parameter
(by @elprans in afdb05c7 for #1187)
* Test and build on Python 3.13
(by @elprans in 3aa98944 for #1188)
* Support PostgreSQL 17
(by @elprans in cee97e1a for #1189)
(by @MeggyCal in aa2d0e69 for #1185)
* Add `fetchmany` to execute many *and* return rows
(by @rossmacarthur in 73f2209d for #1175)
* Add `connect` kwarg to …
> asyncpg v0.30.0

- asyncpg/connect_utils.py
I noticed that it would be very useful to have a fully typed `connection_utils` as it is the core for a lot of other modules that interact with the `connect.Connection`.
This just adds some basic parameter annotation that is pretty straightforward. I have also decided to be pragmatic and add a `TODO` for stuff that is just too hard right now. We can always revisit cases like this if we ever do want to enable a type checker. In the meantime, having callers of the internal function `_create_ssl_connection` get the correct type already helps with typing the public API correctly.
> Add typing to two objects in `connection_utils`

- asyncpg/pool.py
In an effort to add more type annotations to common interfaces I decided to tackle some of the simpler methods. Also, to familiarise myself with the CI and project.
There is nothing groundbreaking in this PR. It:
- Adds `-> None` for functions that are not returning anything
- Expands one `__aexit__` to be the correct full type
- Types the arguments and attributes of `PoolConnectionHolder`, `PoolConnectionProxyMeta` and `PoolAcquireContext` based on actual usage patterns.
Let me know if there are any questions. I didn't really see any style checking recommendations in the documentation or `setup.py` so just used what `black`, `ruff` and others have decided is the de facto style of "modern" Python code.
> Add typing to auxiliary classes around `Pool`

- asyncpg/types.py
I'm glad to see some type hints were added in 0.30.0! I tried them out, and encountered a minor issue.
In order for the `_RangeValue` protocol to type check properly, it needs to reference the created `TypeVar`, not itself.
Both pyright and mypy show a ton of errors when type checking this before these changes. (I've omitted non-relevant errors here):
```
% pyright tests/test_types.py
/Users/dmcgee/projects/sbl/asyncpg/tests/test_types.py
/Users/dmcgee/projects/sbl/asyncpg/tests/test_types.py:18:25 - error: Argument of type "Literal[1]" cannot be assigned to parameter "lower" of type "_RV@Range | None" in function "__init__"
  Type "Literal[1]" is not assignable to type "_RV@Range | None"
    Type "Literal[1]" is not assignable to type "_RangeValue"
      "Literal[1]" is incompatible with …
```
> Fix typing issues around Range/RangeValue

- tests/test_connect.py
A fix for python/cpython#105704 broke parsing of URIs containing
multiple hosts if one or all of the hosts are IPv6 address literals.
This blocks CI, so disable those tests for now until this is fixed
properly.
> Disable connection URI tests broken by a recent Python fix

- asyncpg/connection.py
- asyncpg/introspection.py
Type codec setup functions will no longer attempt to introspect the type
if it's one of the known builtin types.
Fixes: #1206
Fixes: #1138
Fixes: #1242
> Avoid performing type introspection on known types

- asyncpg/connection.py
- asyncpg/pool.py
- asyncpg/prepared_stmt.py
The latest version of Pyright makes calling a function with an "implicit optional" a type error. An "implicit optional" is like  the following code, where a parameter is annotated with a type that doesn't include `None` but the default value is `None`:
```python
def foo(arg: int = None):
pass
```
More info here: https://docs.astral.sh/ruff/rules/implicit-optional/
This PR adds `typing.Optional` where necessary.
> Fix "implicit optional", e.g. `arg: int = None`

- asyncpg/connect_utils.py
- tests/test_connect.py
Currently when using multiple hosts asyncpg requires there be one port per host. Per the postgres [documentation](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-MULTIPLE-HOSTS). "As an exception, if only one port is specified, it applies to all the hosts.".
This PR attempts to fix this inconsistency between libpq and asyncpg.
> Fix multi port connection string issue

- asyncpg/connection.py
We allow disabling the statement cache to circumvent a proxy's inability to
cope with them, however there are still some holes where the use of a named
statement is attempted: `prepare()` with the default arguments, and
`copy_in()`.  Fix both so that the use of a named statement is dependent
upon whether the prepared statement cache is enabled.
Fixes: #1219
Closes: #1218
> Make `prepare()` not use named statements by default when cache is disabled
